// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJhzU6RzHI-l2aDBwUzlLJRs8N_dxjQGo',
    appId: '1:838261028996:web:29dff6273301d16cb76ad1',
    messagingSenderId: '838261028996',
    projectId: 'beauteapp-a78cb',
    authDomain: 'beauteapp-a78cb.firebaseapp.com',
    storageBucket: 'beauteapp-a78cb.appspot.com',
    measurementId: 'G-SGEGW1QN5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgE43MrFpFFuuCwz-Pilwqr1nyhVrTBuU',
    appId: '1:838261028996:android:d646cf2f4e886c21b76ad1',
    messagingSenderId: '838261028996',
    projectId: 'beauteapp-a78cb',
    storageBucket: 'beauteapp-a78cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO0D-kJP1BYUa1P97CzJY1tgmqAGjLia0',
    appId: '1:838261028996:ios:a26bab210c6248d7b76ad1',
    messagingSenderId: '838261028996',
    projectId: 'beauteapp-a78cb',
    storageBucket: 'beauteapp-a78cb.appspot.com',
    iosBundleId: 'com.example.beauteApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO0D-kJP1BYUa1P97CzJY1tgmqAGjLia0',
    appId: '1:838261028996:ios:c4d986714ca137f8b76ad1',
    messagingSenderId: '838261028996',
    projectId: 'beauteapp-a78cb',
    storageBucket: 'beauteapp-a78cb.appspot.com',
    iosBundleId: 'com.example.beauteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJhzU6RzHI-l2aDBwUzlLJRs8N_dxjQGo',
    appId: '1:838261028996:web:bcdc0c9cdda8ee33b76ad1',
    messagingSenderId: '838261028996',
    projectId: 'beauteapp-a78cb',
    authDomain: 'beauteapp-a78cb.firebaseapp.com',
    storageBucket: 'beauteapp-a78cb.appspot.com',
    measurementId: 'G-P7217H4W0X',
  );
}
